### ISSUE TITLE
RP2040_RTC_Time crashes Pico, does not work

### ISSUE THREAD

**Issue by maxgerhardt** [khoih-prog/RP2040_RTC#3] opened 2021-11-01 15:01 UTC
### Describe the bug

Using the https://github.com/khoih-prog/RP2040_RTC/tree/main/examples/Time/RP2040_RTC_Time example on a Raspberry Pi Pico does not work.

### Steps to Reproduce

Open the https://github.com/khoih-prog/RP2040_RTC/tree/main/examples/Time/RP2040_RTC_Time example, set the board to "Arduino Mbed OS RP2040 boards" -> Raspberry Pi Pico, compile and uplaod the sketch. Observe the serial monitor.

### Expected behavior

The sketch sets the current RTC time as dictated by `currTime = { 2021, 9, 30, 4, 4, 0, 0 };` and prints the current time on the serial monitior.

### Actual behavior

Hangup after the sketch outputs

```
Start RP2040_RTC_Time on MBED RASPBERRY_PI_PICO
RP2040_RTC v1.0.6
Timezone_Generic v1.7.1
```

In fact when adding a few print statements in `setup()` as 

```cpp
  Serial.println("Creating new timezone.."); Serial.flush();
  myTZ = new Timezone(myDST, mySTD);

  // Start the RTC
  Serial.println("rtc_init().."); Serial.flush();
  rtc_init();

  Serial.println("rtc_set_datetime().."); Serial.flush();
  rtc_set_datetime(&currTime);
```

The serial monitor outputs
```
Start RP2040_RTC_Time on MBED RASPBERRY_PI_PICO
RP2040_RTC v1.0.6
Timezone_Generic v1.7.1
Creating new timezone..
```
hinting at that it did not survive the line `myTZ = new Timezone(myDST, mySTD);`. 

After that, the on-board LED goes into a fast blinking pattern, meaning the board has landed in [`mbed_die()`](https://github.com/ARMmbed/mbed-os/blob/07e119b46754fc313947f3ce8399c68a613f0c77/platform/source/mbed_board.c#L26-L53) after a fatal error.

### Debug and AT-command log (if applicable)

See above.

### Screenshots

None.

### Information

* Arduino IDE version: 1.8.13
* `RP2040` Core Version: Arduino-mbed RP2040 v2.5.2 (latest)
* `RP2040` Board type: RASPBERRY_PI_PICO
* Contextual information (e.g. what you were trying to achieve): Run the simplest library exaemple
* Simplest possible steps to reproduce: Done per above
* Anything that might be relevant in your opinion, such as:
  * Operating system: Windows 10 x64

**Comment by maxgerhardt** [comment] 2021-11-01 15:33
If I use the EarlePhillhower core instead of ArduinoCore-Mbed, I get much further

```
Start RP2040_RTC_Time on RASPBERRY_PI_PICO
RP2040_RTC v1.0.6
Timezone_Generic v1.7.1
Creating new timezone..
rtc_init()..
rtc_set_datetime()..
============================
04:00:01 Thu 30 Sep 2021 UTC
00:00:01 Thu 30 Sep 2021 EDT
============================
04:00:11 Thu 30 Sep 2021 UTC
00:00:11 Thu 30 Sep 2021 EDT
============================
04:00:21 Thu 30 Sep 2021 UTC
00:00:21 Thu 30 Sep 2021 EDT
============================
04:00:31 Thu 30 Sep 2021 UTC
00:00:31 Thu 30 Sep 2021 EDT
```

**Comment by khoih-prog** [comment] 2021-11-01 17:50
Hi @maxgerhardt 

Thanks for the bug report.

I've just tested using the same settings but still could duplicate the crash.

I wonder if there is any difference in actual installation, bad boards, etc. Could you please check and verify

![Selection_070](https://user-images.githubusercontent.com/57012152/139716493-91ebd637-9e6c-4629-a086-a962bbcc2719.png)

```
Start RP2040_RTC_Time on MBED RASPBERRY_PI_PICO
RP2040_RTC v1.0.6
Timezone_Generic v1.7.1
============================
04:00:01 Thu 30 Sep 2021 UTC
00:00:01 Thu 30 Sep 2021 EDT
============================
04:00:11 Thu 30 Sep 2021 UTC
00:00:11 Thu 30 Sep 2021 EDT
============================
04:00:21 Thu 30 Sep 2021 UTC
00:00:21 Thu 30 Sep 2021 EDT
============================
04:00:31 Thu 30 Sep 2021 UTC
00:00:31 Thu 30 Sep 2021 EDT
============================
04:00:41 Thu 30 Sep 2021 UTC
00:00:41 Thu 30 Sep 2021 EDT
============================
04:00:51 Thu 30 Sep 2021 UTC
00:00:51 Thu 30 Sep 2021 EDT
============================
04:01:01 Thu 30 Sep 2021 UTC
00:01:01 Thu 30 Sep 2021 EDT
============================
04:01:11 Thu 30 Sep 2021 UTC
00:01:11 Thu 30 Sep 2021 EDT
============================
04:01:21 Thu 30 Sep 2021 UTC
00:01:21 Thu 30 Sep 2021 EDT
============================
04:01:31 Thu 30 Sep 2021 UTC
00:01:31 Thu 30 Sep 2021 EDT
============================
04:01:41 Thu 30 Sep 2021 UTC
00:01:41 Thu 30 Sep 2021 EDT
============================
04:01:51 Thu 30 Sep 2021 UTC
00:01:51 Thu 30 Sep 2021 EDT
============================
04:02:01 Thu 30 Sep 2021 UTC
00:02:01 Thu 30 Sep 2021 EDT
============================
04:02:11 Thu 30 Sep 2021 UTC
00:02:11 Thu 30 Sep 2021 EDT
============================
04:02:21 Thu 30 Sep 2021 UTC
00:02:21 Thu 30 Sep 2021 EDT
============================
04:02:31 Thu 30 Sep 2021 UTC
00:02:31 Thu 30 Sep 2021 EDT
============================
04:02:41 Thu 30 Sep 2021 UTC
00:02:41 Thu 30 Sep 2021 EDT
============================
04:02:51 Thu 30 Sep 2021 UTC
00:02:51 Thu 30 Sep 2021 EDT
============================
04:03:01 Thu 30 Sep 2021 UTC
00:03:01 Thu 30 Sep 2021 EDT
============================
04:03:11 Thu 30 Sep 2021 UTC
00:03:11 Thu 30 Sep 2021 EDT
============================
04:03:21 Thu 30 Sep 2021 UTC
00:03:21 Thu 30 Sep 2021 EDT
============================
04:03:31 Thu 30 Sep 2021 UTC
00:03:31 Thu 30 Sep 2021 EDT
============================
04:03:41 Thu 30 Sep 2021 UTC
00:03:41 Thu 30 Sep 2021 EDT
============================
04:03:51 Thu 30 Sep 2021 UTC
00:03:51 Thu 30 Sep 2021 EDT
============================
04:04:01 Thu 30 Sep 2021 UTC
00:04:01 Thu 30 Sep 2021 EDT
============================
04:04:11 Thu 30 Sep 2021 UTC
00:04:11 Thu 30 Sep 2021 EDT
============================
04:04:21 Thu 30 Sep 2021 UTC
00:04:21 Thu 30 Sep 2021 EDT
============================
04:04:31 Thu 30 Sep 2021 UTC
00:04:31 Thu 30 Sep 2021 EDT
```

**Comment by khoih-prog** [comment] 2021-11-01 17:54
I'm using

- Ubuntu 20.04 LTS
- Arduino IDE v1.8.16
- `RP2040` Core Version: Arduino-mbed RP2040 v2.5.2 (latest)
- `RP2040` Board type: RASPBERRY_PI_PICO

**Comment by maxgerhardt** [comment] 2021-11-01 17:56
I'm updating to the same Arduino IDE version now to see if that makes a difference. We're already on the same core & library version it seems. If that does not help, I'll check in Ubuntu.

**Comment by maxgerhardt** [comment] 2021-11-01 18:26
I have a *clean* install of Ubuntu 20.04 in a virtual machine, Arduino IDE 1.8.16, ArduinoCore-mbed 2.5.2 and all the needed latest libraries installed via the Arduino IDE library managed, and it still fails the same way as it did on Windows.

![grafik](https://user-images.githubusercontent.com/26485477/139721836-b4142a5a-a912-4b8e-aa3e-b79db68fb6e8.png)

I cannot get this to work.

**Comment by maxgerhardt** [comment] 2021-11-01 18:47
The Timezone_Generic code attempts to open a filesystem on the Pico. Do I have to use any special tool to initialize that filesystem?

**Comment by khoih-prog** [comment] 2021-11-01 19:31
> The Timezone_Generic code attempts to open a filesystem on the Pico. Do I have to use any special tool to initialize that filesystem?

I think Timezone_Generic relies on RP2040 LittleFS for certain examples requiring storage as mentioned in [**Currently Supported Storage**](https://github.com/khoih-prog/Timezone_Generic#currently-supported-storage)

The library to use for mbed core is [**LittleFS_Mbed_RP2040**](https://github.com/khoih-prog/LittleFS_Mbed_RP2040)

Still has some bug in the core for **Nano_RP2040_Connect** as in [Important Notes](https://github.com/khoih-prog/LittleFS_Mbed_RP2040#important-notes) and [RP2040 Connect board has faulty components in newest purchase #318](https://github.com/arduino/ArduinoCore-mbed/issues/318#)

But OK for RP2040

**Comment by khoih-prog** [comment] 2021-11-01 19:33
That's the reason why no crash if using `EarlePhilhower` instead of `ArduinoCore-Mbed` core

**Comment by maxgerhardt** [comment] 2021-11-01 19:54
Using the [LittleFS_Test.ino](https://github.com/khoih-prog/LittleFS_Mbed_RP2040/blob/main/examples/LittleFS_Test/LittleFS_Test.ino) sketch I just get

```

Start LittleFS_Test on RaspberryPi Pico
LittleFS_Mbed_RP2040 v1.0.2
[LFS] LittleFS size (KB) = 64
[LFS] LittleFS Mount Fail
[LFS] Formatting... 
```
followed by a crash (LED is blinking in a rapid pattern again, indicating it landed in `mbed_die()` after a crash).

So it looks like indeed the crash happens in the LittleFS logic.

My flash chip has the following markings on it

![grafik](https://user-images.githubusercontent.com/26485477/139732859-92f60f45-120d-471f-a01b-27f0ef652258.png)

Which seem to read "1P033 00148S"(?). So it's definitely not an ILS chip that causes the known problem, the reference flash chip has a big "ILS" on it.

**Comment by khoih-prog** [comment] 2021-11-01 19:59
This is really strange,

I just tested and OK with my board. I'm afraid there is some issue with your RP2040 with recent component shortage, quality + QC

```
Start LittleFS_Test on RaspberryPi Pico
LittleFS_Mbed_RP2040 v1.0.2
[LFS] LittleFS size (KB) = 64
[LFS] LittleFS Mount OK
====================================================
Writing file: /littlefs/hello1.txt => Open OK
* Writing OK
====================================================
Reading file: /littlefs/hello1.txt => Open OK
Hello from RaspberryPi Pico
====================================================
Appending file: /littlefs/hello1.txt => Open OK
* Appending OK
====================================================
Reading file: /littlefs/hello1.txt => Open OK
Hello from RaspberryPi Pico
Hello from RaspberryPi Pico
====================================================
Renaming file: /littlefs/hello1.txt to: /littlefs/hello2.txt => OK
====================================================
readCharsFromFile: /littlefs/hello2.txt => Open OK
Hello from RaspberryPi Pico
Hello from RaspberryPi Pico
====================================================
Deleting file: /littlefs/hello2.txt => OK
====================================================
Reading file: /littlefs/hello2.txt => Open Failed
====================================================
Testing file I/O with: /littlefs/hello1.txt => Open OK
- writing

16 Kbytes written in (ms) 236
====================================================
- reading

16 Kbytes read in (ms) 5
====================================================
Testing file I/O with: /littlefs/hello2.txt => Open OK
- writing

16 Kbytes written in (ms) 246
====================================================
- reading

16 Kbytes read in (ms) 6
====================================================
Deleting file: /littlefs/hello1.txt => OK
====================================================
Deleting file: /littlefs/hello2.txt => OK
====================================================

Test complete
```

Can you try LittleFS to verify the Flash is OK or some new bug of the core ???

1. directly from the mbed core
2. EarlePhilhower core

**Comment by maxgerhardt** [comment] 2021-11-01 20:04
In fact per [schematics](https://proto-pic.co.uk/wp-content/uploads/2021/03/RPI-PICO-R3-PUBLIC-SCHEMATIC.pdf) a Pico should have a Winbond W25Q16JVUXIQ chip, and per [datasheet](https://www.mouser.de/datasheet/2/949/w25q16jv_spi_revg_03222018_plus-1489727.pdf) page 73 the USON-8 package of that chip has a top-side marking of 

![grafik](https://user-images.githubusercontent.com/26485477/139734016-d50d2613-0db7-4287-a1a1-b007204f77c7.png)

With notes

>USON has special top side marking due to size limitation 
> yww = date code (year, work week); xxxx = lot ID

So if I re-read my "1P033 0Q148S" (misread a Q as a 0) this seems to make sense, year "0" might be 202**0**, week 33 (the chip came out in 2016 so 2010 makes no sense).

So I should have a standard Winbond chip.

**Comment by khoih-prog** [comment] 2021-11-01 20:05
Did you `FORCE_REFORMAT` in [LittleFS_Test.ino#L22](https://github.com/khoih-prog/LittleFS_Mbed_RP2040/blob/main/examples/LittleFS_Test/LittleFS_Test.ino#L22)

```
#define FORCE_REFORMAT          true
```

**Comment by maxgerhardt** [comment] 2021-11-01 20:05
Nope, I left the standard settings be which is `false`. It then auto-detected that it needed to reformat.

**Comment by khoih-prog** [comment] 2021-11-01 20:08
Possible `true` is necessary for the 1st try ???
Long time ago and I don't remember now if auto format is taking place. Just try `true` to see.

**Comment by maxgerhardt** [comment] 2021-11-01 20:09
Interesting, with that it reformats it.. successfully..

```

Start LittleFS_Test on RaspberryPi Pico
LittleFS_Mbed_RP2040 v1.0.2
[LFS] LittleFS size (KB) = 64
[LFS] LittleFS Mount OK
====================================================
Writing file: /littlefs/hello1.txt => Open OK
* Writing OK
====================================================
Reading file: /littlefs/hello1.txt => Open OK
Hello from RaspberryPi Pico
```

**Comment by maxgerhardt** [comment] 2021-11-01 20:11
I re-uploaded the RTC Time sketch after the LittleFS test was done, but it still fails in the exact same place and crashes sadly :(

**Comment by khoih-prog** [comment] 2021-11-01 20:13
OK, so we have to use `true` the first time as in

[LittleFS_Mbed_RP2040.hpp#L22-L31](https://github.com/khoih-prog/LittleFS_Mbed_RP2040/blob/main/src/LittleFS_Mbed_RP2040.hpp#L22-L31)

```
bool LittleFS_MBED::init()
{
  LFS_LOGERROR1("LittleFS size (KB) = ", RP2040_FS_SIZE_KB);

#if FORCE_REFORMAT
  fs.reformat(&bd);
#endif  

  return mount();
}
```

No auto-reformat was designed in then. Will have a look in the future.

**Comment by maxgerhardt** [comment] 2021-11-01 20:31
After an initial LittleFS format of the Flash, it **has** to work without re-formatting it a second time. This cannot be. There must be a bug somewhere.

I've edited Timezone_Generic code in initStorage from

```
#elif TZ_USE_MBED_RP2040
 
      TZ_LOGDEBUG1("LittleFS size (KB) = ", RP2040_FS_SIZE_KB);
      int err = fs.mount(&bd);
      
      if (err)
      {       
        // Reformat if we can't mount the filesystem
        TZ_LOGERROR("LittleFS Mount Fail. Formatting... ");
        TZ_FLUSH;
 
        err = fs.reformat(&bd);
      }
```
to

```
#elif TZ_USE_MBED_RP2040
 
      TZ_LOGDEBUG1("LittleFS size (KB) = ", RP2040_FS_SIZE_KB);
      fs.reformat(&bd);
      int err = fs.mount(&bd);
      
      if (err)
      {       
        // Reformat if we can't mount the filesystem
        TZ_LOGERROR("LittleFS Mount Fail. Formatting... ");
        TZ_FLUSH;
 
        err = fs.reformat(&bd);
      }
```

But it still outputs the same thing. Even after adding significant amount of `Serial.println()` in the constructor etc, I can't seem to get more debug output out of it. Extremely strange, I'll look into it.

**Comment by maxgerhardt** [comment] 2021-11-01 20:40
This is **freaking absurd**. 

If I do an extremely minimal test in a new sketch

```cpp
class MyTestObj {
private:
  int attr = 0;
public:
  MyTestObj(int attr) {
    Serial.println("Inside constructor!"); Serial.flush(); delay(100);
    this->attr = attr;
    Serial.println("Set attribute!"); Serial.flush(); delay(1000);
  }
};


void setup() {
  Serial.begin(115200);
  while (!Serial);

  delay(200);

  auto x = new MyTestObj(1);
  Serial.println("Back again!"); Serial.flush(); delay(1000);
  delete x;   
  Serial.println("Deleted!"); Serial.flush(); delay(1000);
}

void loop() {
  // put your main code here, to run repeatedly:

}
```
I cannot get past the line 

```cpp
    this->attr = attr;
```

it seems that the `new` operator allocates.. completely invalid memory?! And just crashes the freaking board!! I just get up to

```
Inside constructor!
```

**Comment by maxgerhardt** [comment] 2021-11-01 20:50
Okay no that's wrong. I can't get past **Serial.flush()**. That immediately crashes. I added that in to make sure I see the output before it crashes, but in this case it seems to cause a crash. Retesting without..

**Comment by maxgerhardt** [comment] 2021-11-01 20:53
That's it. After having formatted LittleFS once with the other test sketch, the Time sketch now works too.

```

Start RP2040_RTC_Time on MBED RASPBERRY_PI_PICO
RP2040_RTC v1.0.6
Timezone_Generic v1.7.1
Creating new timezone..
[TZ] LittleFS size (KB) =  64
[TZ] LittleFS Mount OK
rtc_init()..
rtc_set_datetime()..
============================
04:00:01 Thu 30 Sep 2021 UTC
00:00:01 Thu 30 Sep 2021 EDT
============================
04:00:11 Thu 30 Sep 2021 UTC
00:00:11 Thu 30 Sep 2021 EDT
```

But I think some improvement still has to be done there for the autoformat. If it crashes in ArduinoCore-mbed before the library can detect that mounting failed, a bug needs to be reported there.

**Comment by khoih-prog** [comment] 2021-11-01 21:36
Still a bug somewhere.

Possibly something breaking just introduced from the new mbed core **v2.4.1 / v2.5.2** as I fully tested the library using latest core v2.3.1 then and didn't see any issue.

Check [**Prerequisites**](https://github.com/khoih-prog/LittleFS_Mbed_RP2040#prerequisites), but now I don't remember the full picture what happened then.

I'll retest [LittleFS_Mbed_RP2040 Library](https://github.com/khoih-prog/LittleFS_Mbed_RP2040) using new cores if having time

**Comment by khoih-prog** [comment] 2021-11-01 22:27
Try with several RP2040 boards, using **v2.5.2**, using `EarlePhilhower`then `ArduinoCore-Mbed` core, back-and-forth, increase / decrease flash size, FORCE_REFORMAT = `true / false`, still can't duplicate the issue.

It seems **board-dependent or some kind of stray-pointers (in the core ??)** and I don't think I can solve this issue now. So I'm closing it now until I get the correct `bad board` and/or can duplicate, or someone can make a PR after location the bug of this library.

Thanks anyway,

**Closed by khoih-prog** 2021-11-01 22:27 UTC

**Comment by maxgerhardt** [comment] 2021-11-02 09:13
>It seems board-dependent or some kind of stray-pointers (in the mbed core ??) and I don't think I can solve this issue now without being able to duplicate.

No, I don't think it's that, it has to do with the filesystem.

I can 100% reproduce the problem by putting the Pico into bootloader mode again and dragging the [`flash_nuke.uf2`](https://learn.adafruit.com/getting-started-with-raspberry-pi-pico-circuitpython/circuitpython#flash-resetting-uf2-3083182-8) on it. Then the flash is all cleared (and LittleFS is thus also reset) to 0xff again. Reuploading the RP2040_RTC_Time sketch then always crashes with

```
Start RP2040_RTC_Time on MBED RASPBERRY_PI_PICO
RP2040_RTC v1.0.6
Timezone_Generic v1.7.1
```

and that is **always reproducable**. 

The sketch won't work unless I do a forced reformat with the LittleFS sketch and reupload the original sketch. As soon as the flash is reset, the RTC_Time sketch crashes the board again.

**Comment by khoih-prog** [comment] 2021-11-02 15:52
With the fix, [**LittleFS_Mbed_RP2040**](https://github.com/khoih-prog/LittleFS_Mbed_RP2040) is OK now, but still causing crash if using this [**RP2040_RTC** library](https://github.com/khoih-prog/RP2040_RTC).

Will find out why and fix.

**Comment by khoih-prog** [comment] 2021-11-02 16:27
The [LittleFS_Mbed_RP2040 releases v1.0.3](https://github.com/khoih-prog/LittleFS_Mbed_RP2040/releases/tag/v1.0.3) has just been published in both Arduino and PIO Library Manager

---

### Releases v1.0.3

1. Fix crashing issue for new flash. Check [RP2040_RTC_Time crashes Pico, does not work #3](https://github.com/khoih-prog/RP2040_RTC/issues/3)

**Comment by khoih-prog** [comment] 2021-11-02 16:37
Hi @maxgerhardt 

It turns out that the same `TZ_FLUSH` at [Timezone_Generic_Impl.h#L474](https://github.com/khoih-prog/Timezone_Generic/blob/main/src/Timezone_Generic_Impl.h#L474) is causing crash. Will fix and release a new version.

```
TZ_FLUSH;
```

Really strange, but I don't have time to investigate what's new in cores v2.5.2 and v2.4.1 to cause the crash.

**Comment by maxgerhardt** [comment] 2021-11-02 16:44
Yep, `Serial.flush()` instantly kills the processor, I fell in that trap above too. This needs to be reported in the core.

**Comment by khoih-prog** [comment] 2021-11-02 16:47
> Yep, Serial.flush() instantly kills the processor, I fell in that trap above too. This needs to be reported in the core.

Could you please help report the `flush` issue of the [Arduino-mbed](https://github.com/arduino/ArduinoCore-mbed) core.

Thanks.

**Comment by maxgerhardt** [comment] 2021-11-02 16:53
Yes, writing the issue now.

**Comment by maxgerhardt** [comment] 2021-11-02 16:57
We now depend on https://github.com/arduino/ArduinoCore-mbed/issues/357.

**Comment by khoih-prog** [comment] 2021-11-02 16:59
Thanks.

At least now we can survive without the `flush`

**Comment by khoih-prog** [comment] 2021-11-02 17:20
The underlying [Timezone_Generic releases v1.7.2](https://github.com/khoih-prog/Timezone_Generic/releases/tag/v1.7.2) has just been published to fix this crashing issue.

Thanks for your valuable [**Contributions**](https://github.com/khoih-prog/Timezone_Generic#contributions-and-thanks)

---

### Releases v1.7.2

1. Fix crashing issue for new cleared flash. Check [RP2040_RTC_Time crashes Pico, does not work #3](https://github.com/khoih-prog/RP2040_RTC/issues/3)
